import {
    StyleSheet
} from "react-native";
import   System   from "../Public/System.js";
export  default FunnyStyle = StyleSheet.create({
    main:{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    statusBar:{
        paddingTop:System.y,
        height:42 + System.y,
        backgroundColor:"#FFFFFF",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"flex-start"
    },
    statusBarTags:{
        width:System.width - 42,
        height:42,
        paddingLeft:6,
        paddingRight:6,
    },
    statusBarSoso:{
        width:42,
        height:42,
    },
    statusBarTagItem:{
        fontSize:17,
        lineHeight:42,
        color:"#383838",
        marginLeft:6,
        marginRight:6
    },
    statusBarSosoImg:{
        height:20,
        width:20,
        marginTop:11,
        marginBottom:11,
        marginLeft:11
    },
    videoBox:{
        flex:1
    },
    videoItem:{
        width:System.width
    },
    videoItemT:{
        height:(System.width/16)*9,
        width:System.width,
    },
    videoItemTImg:{
        height:(System.width/16)*9,
        width:System.width,
    },
    videoItemTitle:{
        position:"absolute",
        height:60
    },
    videoItemTitleImg:{
        width:System.width,
        height:60
    },
    videoItemTitleText:{
        position:"absolute",
        flexWrap:"wrap",
        width:System.width,
        color:"#FFF",
        fontSize:17,
        left:0,
        top:0,
        paddingTop:8,
        paddingRight:8,
        paddingLeft:8
    },
    videoItemPlay:{
        position:"absolute",
        height:40,
        width:40,
        top: ((System.width/16)*9 - 40)/2,
        left : (System.width - 40)/2,
        backgroundColor:"rgba(22,22,22,0.618)",
        borderRadius:21
    },
    videoItemPlayImage:{
        height:24,
        width:24,
        marginLeft:9,
        marginTop:8
    },
    videoItemB:{
        width:System.width,
        flexDirection:"row",
        height:44,
        backgroundColor:"#FFF"
    },
    videoItemBL:{
        flex:1,
        flexDirection:"row",
        height:44,
    },
    videoItemBLName:{
        fontSize:14,
        color:"#383838",
        paddingLeft:6,
        height:44,
        lineHeight:44
    },
    videoItemBR:{
        flex:1,
        height:44,
        flexDirection:"row",
        justifyContent:"flex-end",
    },
    videoItemBLImg:{
        height:24,
        width:24,
        marginTop:10,
        marginLeft:10,
        borderRadius:12,
        borderWidth:1,
        borderColor:"#ccc"
    },
    videoItemBRImg:{
        height:20,
        width:20,
        marginTop:12,
        marginRight:12
    },
    action:{
        color:'#d23c3e',
        fontSize:18,
    },
    close : {
        color:"#383838",
        fontSize:17,
    }
});