import {
    StyleSheet
} from "react-native";
import System from "../Public/System";
export  default RemindStyle = StyleSheet.create({
    statusBarX:{
        flexDirection:"row",
        paddingTop:System.y,
        height:42+System.y,
        paddingBottom:6,
        backgroundColor:"#d23c3e",
    },
    statusBarItem1:{
        width:48,
        paddingLeft:12,
        paddingRight:12,
        justifyContent:"center"
    },
    statusBarItem2:{
        flex: 1,
        height:30,
        marginTop:3,
        flexDirection:"row",
        justifyContent:"flex-start",
        alignItems:"center",
        backgroundColor:"#FFF",
        borderRadius:5,
        color:"#FFF"
    },
    statusBarItem2Img:{
        width:15,
        height:15,
        marginLeft:12
    },
    statusBarItem2Text:{
        color:"#666",
        fontSize:14,
        paddingLeft:6
    },
    statusBarItem3:{
        width:48,
        paddingLeft:12,
        paddingRight:12,
        justifyContent:"center",
        color:"#FFF"
    },
    iconItem:{
        height:20,
        width:20,
        marginLeft:2,
        alignItems:"center"
    },
    textItem:{
        color:"#FFF",
        letterSpacing:1,
        fontSize:10,
        marginTop:2,
        textAlign:"center"
    },
    statusBar:{
        height:38,
        backgroundColor:"#FFF",
        flexDirection:"row",
        justifyContent:"flex-start",
        paddingLeft:4,
        paddingRight:4,
        borderBottomWidth:1,
        borderBottomColor:"#DDD"
    },
    statusBarTags:{
        height:39,
        marginLeft:0,
        padding:0,
        paddingRight:50,
        paddingLeft:6,
        backgroundColor:"#FFF",
        borderBottomWidth:1,
        borderBottomColor:"#F1F1F1"
    },
    statusBarSoso:{
        width:42,
        height:38,
        position:"absolute",
        left: System.width - 42,
        top: 42+System.y,
        zIndex:999,
        backgroundColor:"#FFF",
        alignItems:"center",
        justifyContent:"center",
    },
    statusBarTagBox:{
        paddingLeft:8,
        paddingRight:8,
        justifyContent:"center",
    },
    statusBarTagItemBox:{
        alignItems:"center",
        justifyContent:"center",
        borderBottomWidth:2,
        borderBottomColor:"red",
        height:36,
        lineHeight:36,
    },
    statusBarTagItem:{
        fontSize:17,
        padding:0,
        margin:0,
        color:"#383838"
    },
    statusBarSosoImg:{
        height:24,
        width:24
    },
    statusBarSosoImg1:{
        height:18,
        width:18
    },
    statusBarTagItemImg:{
        height:20,
        width:20,
        marginBottom:8
    },
    articleBox:{
        flex:1,
        width:System.width,
        backgroundColor:"#FFF"
    },
    articleItem:{
        width : System.width - 24,
        marginLeft:12,
        marginRight:12,
        paddingTop:6,
        paddingBottom:6,
        borderBottomWidth:1,
        borderBottomColor:"#F1F1F1",
    },
    articleItemTitle1:{
        flex:0.66
    },
    articleItemCover2:{
        flex:0.34
    },
    articleItemTitleText:{
        fontSize:15,
        color:"#383838",
        lineHeight:20
    },
    articleItemCover:{
        height:72,
        marginTop:6,
        marginBottom:6,
        width:System.width - 24,
        flexDirection:"row"
    },
    articleItemCoverImg1:{
        backgroundColor:"#ddd",
        flex:1,
        marginRight:4
    },
    articleItemCoverImg2:{
        backgroundColor:"#ddd",
        flex:1
    },
    articleItemDesc:{
        flexDirection:"row"
    },
    articleItemDescL:{
        height:18,
        flex:0.8,
        justifyContent:"flex-start",
        alignItems:"center",
        flexDirection:"row"
    },
    articleItemDescText:{
        color:"#666",
        fontSize:12,
        lineHeight:18,
        marginRight:12
    },
    articleItemDescR:{
        height:18,
        flex:0.2,
        alignItems:"center",
        justifyContent:"flex-end",
        flexDirection:"row"
    },
    articleItemDescRImg:{
        height:15,
        width:15
    },
    action:{
        color:'#d23c3e',
        fontSize:18,
    },
    close : {
        color:"#383838",
        fontSize:17,
    },
    tabBarLine: {
        backgroundColor:"#FFF",
        height:0
    },
    itemLayout: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center"
    },
    tabStyle: {
        height:38,
        paddingLeft:6,
        paddingRight:6,
        backgroundColor:"#FFF"
    }
});